name: Test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get Changed Files
      uses: hestonhoffman/changed-lines@v1
      with:
        file_filter: '.rb'
      id: changed-files
      
    - name: Print Changed Files and Lines
      continue-on-error: true
      run: echo ${{ steps.changed-files.outputs.changed_lines }}